// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Web.Data;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Description = "A high-performance laptop for work and gaming.",
                            Name = "Laptop 1",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Description = "A sleek smartphone with a powerful camera.",
                            Name = "Smartphone 2",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Audio",
                            Description = "Noise-cancelling headphones for immersive sound.",
                            Name = "Headphones 3",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Home Appliances",
                            Description = "Brew the perfect cup of coffee every morning.",
                            Name = "Coffee Maker 4",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Footwear",
                            Description = "Comfortable running shoes for all terrains.",
                            Name = "Running Shoes 5",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Accessories",
                            Description = "A durable backpack for travel and daily use.",
                            Name = "Backpack 6",
                            Price = 59.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
